[groqcloud]
api_key = "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"

[openai]
api_key = "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"
